In [35]:
# Packages
import gymnasium as gym
from minigrid.core.actions import Actions
from minigrid.minigrid_env import MiniGridEnv
import json
import os
from datetime import datetime
import argparse
import pandas as pd
import time
import random
from sklearn.model_selection import train_test_split
T = 10
env: MiniGridEnv = gym.make(
    id="MiniGrid-BlockedUnlockPickup-v0",
    render_mode = "human",
    tile_size=32,
    agent_view_size=3,
    screen_size=640,
)
obs, _ = env.reset(seed=23)
print(f"obs = {obs}")
obs, *_ = env.step(Actions.forward)
env.close()

obs = {'image': array([[[1, 0, 0],
        [1, 0, 0],
        [1, 0, 0]],

       [[1, 0, 0],
        [1, 0, 0],
        [1, 0, 0]],

       [[1, 0, 0],
        [1, 0, 0],
        [1, 0, 0]]], dtype=uint8), 'direction': 0, 'mission': 'pick up the red box'}


In [36]:
type(obs['image']) 

numpy.ndarray

In [37]:
img = obs['image']

In [38]:
img.T

array([[[6, 5, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [41]:
imgT = img.transpose(1,0,2)

In [42]:
img.shape

(3, 3, 3)

In [46]:
imgT[0]

array([[6, 1, 0],
       [5, 1, 0],
       [1, 0, 0]], dtype=uint8)

In [44]:
imgT[0,0][0]

6

In [34]:
img.transpose(1,0,2)[0][1]

array([5, 1, 0], dtype=uint8)